### ISSUE TITLE
metrix_int table missing

### ISSUE THREAD

**Issue by mercaptan** [NKI-GCF/Metrix#2]
After inserting the sql statements, editing the properties file, compiling the code, and executing 
"java -cp ./lib/mysql-connector-java-5.1.6.jar:. -Dproperties=metrix.properties MetrixDaemon"

I get:
Sep 30, 2013 3:22:03 PM MetrixLogic checkSummary
SEVERE: Error checking for summary by runId in database. com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'metrix.metrix_int' doesn't exist
Exception in thread "Thread-2" java.lang.NullPointerException
    at MetrixLogic.checkTimeout(MetrixLogic.java:289)
    at MetrixLogic.processMetrics(MetrixLogic.java:79)
    at MetrixWatch.checkRegisterIllumina(MetrixWatch.java:116)
    at MetrixWatch.run(MetrixWatch.java:75)

Since I don't currently have a metrix_int table, might that be the culprit?

**Comment by Rhizosis** [comment]
Truely sorry about that. That was a mistake in the commit where it reflects my development database tablename.
In the file DataStore.java (/nki/io/DataStore.java) change the SQL syntax lines to "metrix_objects" instead of "metrix_int".
Recompile and it should work.
I will commit these changes to the repository tomorrow.

**Comment by mercaptan** [comment]
That seems to have done the trick. Thanks!
